### ISSUE TITLE
update wiki/QGIS3Port

### ISSUE THREAD

**Issue by mbernasocchi** [gc-i/wntOS#3]
Hi thanks for the wiki page, we now released a pip package to help you port QGIS plugins, it would be nice if you could update your page
https://github.com/opengisch/qgis2to3/

also, "add QtWidgets import to .py files containing QDialog (other classes could be affected, too; like QWidget or QMessagebox)" this should be taken care of by the qgis fixers.
cheers
MArco

**Comment by tkan** [comment]
Hi Marco,

thank you very much for the input. Glad to see the 2to3 tools are getting more sophisticated to ease the transition. I updated the Wiki page.

All the best,
Thomas

**Comment by mbernasocchi** [comment]
great thanks, one more comment qgis2to3 already includes also the 2to3 scripts from QGIS, so in low bandwidth scenario, it is the quickest way to get all :)
cheers
